---
# defaults file for JTB-Kyndryl-CIC-OS-Settings-Verification-Linux

execute_limits_conf: no
execute_jp1: yes
execute_mq: no
execute_auditd: no

AMI_packages:
  - bc-1.07.1-5.el8.x86_64
  - bind-utils-32:9.11.26-6.el8.x86_64
  - cifs-utils-6.8-3.el8.x86_64
  - cronie-1.5.2-4.el8.x86_64
  - expect-5.45.4-5.el8.x86_64
  - fence-agents-kdump-4.2.1-75.el8.x86_64
  - ftp-0.17-78.el8.x86_64
  - glibc-locale-source-2.28-151.el8.x86_64
  - kexec-tools-2.0.20-34.el8_3.2.x86_64
  - lftp-4.8.4-2.el8.x86_64
  - lsof-4.93.2-1.el8.x86_64
  - langpacks-ja-1.0-12.el8
  - ncompress-4.2.4.4-13.el8.x86_64
  - net-snmp-1:5.8-22.el8.x86_64
  - net-snmp-libs-1:5.8-22.el8.x86_64
  - net-snmp-utils-1:5.8-22.el8.x86_64
  - net-tools-2.0-0.52.20160912git.el8.x86_64
  - nmap-ncat-2:7.70-6.el8.x86_64
  - portreserve-0.0.5-19.el8.x86_64
  - sos-4.1-5.el8
  - strace-5.7-3.el8.x86_64
  - sysstat-11.7.3-6.el8.x86_64
  - tcpdump-14:4.9.3-2.el8.x86_64
  - tk-1:8.6.8-1.el8.x86_64
  - traceroute-3:2.1.0-6.el8.x86_64
  - wget-1.19.5-10.el8.x86_64
  - vsftpd-3.0.3-34.el8.x86_64
  - zip-3.0-23.el8
  - libnsl-2.28-151.el8.x86_64
  - lvm2-8:2.03.12-10.el8
  - amazon-ssm-agent-3.1.821.0-1.x86_64
  - amazon-cloudwatch-agent-1.247349.0b251399-1.x86_64
  - polkit.x86_64
  - polkit-libs.x86_64


# Variables of Packages
group1_packages:
  - cifs-utils-6.8-3.el8.x86_64
  - lftp-4.8.4-2.el8.x86_64
  - net-snmp-utils-1:5.8-22.el8.x86_64

group2_packages:
  - man-pages-4.15-6.el8
  - xfsdump-3.1.8-2.el8.x86_64

lkpbat01.p-ln-svc_packages:
 - binutils-2.30-108.el8_5.1.x86_64
 - glibc-2.28-151.el8.i686
 - glibc-2.28-151.el8.x86_64
 - glibc-devel-2.28-151.el8.i686
 - glibc-devel-2.28-151.el8.x86_64
   # - hinemos-6.2-agent.noarch
 - ksh-20120801-254.el8.x86_64
 - libaio-0.3.112-1.el8.i686
 - libaio-0.3.112-1.el8.x86_64
 - libaio-devel-0.3.112-1.el8.i686
 - libaio-devel-0.3.112-1.el8.x86_64
 - libX11-1.6.8-5.el8.i686
 - libX11-1.6.8-5.el8.x86_64
 - libXau-1.0.9-3.el8.i686
 - libXau-1.0.9-3.el8.x86_64
 - libXi-1.7.10-1.el8.i686
 - libXi-1.7.10-1.el8.x86_64
 - libXtst-1.2.3-7.el8.i686
 - libXtst-1.2.3-7.el8.x86_64
 - libgcc-8.5.0-4.el8_5.i686
 - libgcc-8.5.0-4.el8_5.x86_64                     #8.3.1-5.1.el8 found in lktbat01
 - libstdc++-8.5.0-4.el8_5.x86_64     #it will install both versions x86_64 and i686
 - libstdc++-devel-8.5.0-4.el8_5.i686
 - libstdc++-devel-8.5.0-4.el8_5.x86_64
 - libxcb-1.13.1-1.el8.i686
 - libxcb-1.13.1-1.el8.x86_64
 - libnsl-2.28-151.el8.x86_64
 - libnsl-2.28-151.el8.i686
 - mailx-12.5-29.el8.x86_64
 - make-1:4.2.1-10.el8.x86_64
 - ncompress-4.2.4.4-13.el8.x86_64                   #not found in lktbat01
 - ncurses-6.1-7.20180224.el8.x86_64
 - nfs-utils-1:2.3.3-46.el8.x86_64
 - net-snmp.x86_64
 - net-snmp-libs.x86_64
 - psmisc-23.1-5.el8.x86_64
 - postfix-2:3.5.8-2.el8.x86_64
 - smartmontools-1:7.1-1.el8.x86_64
 - sshpass-1.06-9.el8.x86_64
 - sysstat-11.7.3-6.el8.x86_64
 - xfsdump-3.1.8-2.el8.x86_64

lkpbat02.p-ln-svc_packages:
 - binutils-2.30-108.el8_5.1.x86_64
 - glibc-2.28-151.el8.i686
 - glibc-2.28-151.el8.x86_64
 - glibc-devel-2.28-151.el8.i686
 - glibc-devel-2.28-151.el8.x86_64
   # - hinemos-6.2-agent.noarch
 - ksh-20120801-254.el8.x86_64
 - libaio-0.3.112-1.el8.i686
 - libaio-0.3.112-1.el8.x86_64
 - libaio-devel-0.3.112-1.el8.i686
 - libaio-devel-0.3.112-1.el8.x86_64
 - libX11-1.6.8-5.el8.i686
 - libX11-1.6.8-5.el8.x86_64
 - libXau-1.0.9-3.el8.i686
 - libXau-1.0.9-3.el8.x86_64
 - libXi-1.7.10-1.el8.i686
 - libXi-1.7.10-1.el8.x86_64
 - libXtst-1.2.3-7.el8.i686
 - libXtst-1.2.3-7.el8.x86_64
 - libgcc-8.5.0-4.el8_5.i686
 - libgcc-8.5.0-4.el8_5.x86_64                     #8.3.1-5.1.el8 found in lktbat01
 - libstdc++-8.5.0-4.el8_5.x86_64     #it will install both versions x86_64 and i686
 - libstdc++-devel-8.5.0-4.el8_5.i686
 - libstdc++-devel-8.5.0-4.el8_5.x86_64
 - libxcb-1.13.1-1.el8.i686
 - libxcb-1.13.1-1.el8.x86_64
 - libnsl-2.28-151.el8.x86_64
 - libnsl-2.28-151.el8.i686
 - mailx-12.5-29.el8.x86_64
 - make-1:4.2.1-10.el8.x86_64
 - ncompress-4.2.4.4-13.el8.x86_64                   #not found in lktbat01
 - ncurses-6.1-7.20180224.el8.x86_64
 - nfs-utils-1:2.3.3-46.el8.x86_64
 - net-snmp.x86_64
 - net-snmp-libs.x86_64
 - psmisc-23.1-5.el8.x86_64
 - postfix-2:3.5.8-2.el8.x86_64
 - smartmontools-1:7.1-1.el8.x86_64
 - sshpass-1.06-9.el8.x86_64
 - sysstat-11.7.3-6.el8.x86_64
 - xfsdump-3.1.8-2.el8.x86_64

#    Variables for Services
check_services:
  - postfix.service
  - snmpd.service
  - vsftpd.service
  - irqbalance.service

OUTPUTFILE: ""

# Variables for harddisk1
device_nvme0n1: {"name": "/dev/nvme0n1","size": 40}
device_swap: {"name": "/dev/vg_data1/lv_swap","size": 16}
device_home1: {"name": "/dev/vg_data1/lv_home1","size": 274}

device_nvme1n1: {"name": "/dev/nvme1n1","size": 290}
pv_nvme1n1: /dev/nvme1n1

# Variables for harddisk2
device_nvme2n1: {"name": "/dev/nvme2n1","size": 30}
pv_nvme2n1: /dev/nvme2n1

motd_message: |
           *******************************************************************************
           *                                                                             *
           *                                                                             *
           *  This system must only be used for conducting IJDI's business or            *
           *  for purposes authorized by IJDI management.                                *
           *                                                                             *
           *                                                                             *
           *******************************************************************************
